# Generated by Django 5.2.17 on 2026-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_fa', models.TextField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('rate_cnt', models.IntegerField(null=True)),
                ('category1', models.TextField(null=True)),
                ('category2', models.TextField(null=True)),
                ('brand', models.TextField(null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('seller', models.TextField(null=True)),
                ('is_fake', models.BooleanField(null=True)),
                ('min_price_last_month', models.BigIntegerField(null=True)),
                ('sub_category', models.TextField(null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
