# Generated by Django 5.2.17 on 2026-10-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKpi',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='kpi', serialize=False, to='catalog.products')),
                ('title_fa', models.TextField(null=True)),
                ('raw_product_rate', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('rate_cnt', models.IntegerField(null=True)),
                ('positive_comments', models.IntegerField(null=True)),
                ('negative_comments', models.IntegerField(null=True)),
                ('bayesian_product_score', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('sentiment_score', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('product_health_score', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('product_status', models.TextField(null=True)),
            ],
            options={
                'db_table': 'product_kpi_mv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerKpi',
            fields=[
                ('seller_code', models.TextField(primary_key=True, serialize=False)),
                ('seller_title', models.TextField(null=True)),
                ('sold_products', models.IntegerField(null=True)),
                ('total_comments', models.IntegerField(null=True)),
                ('positive_comments', models.IntegerField(null=True)),
                ('negative_comments', models.IntegerField(null=True)),
                ('customer_satisfaction_score', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('fake_product_percent', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('low_rated_product_percent', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('seller_health_score', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('seller_status', models.TextField(null=True)),
            ],
            options={
                'db_table': 'seller_kpi_mv',
                'managed': False,
            },
        ),
    ]
